import { craftingStyles } from "galadrielcss";
// Importing the CSS file generated by Galadriel.CSS
import "./page.css";

export default function Home() {
    const container = craftingStyles(() => ({
		backgroundImage: "url('/background.jpg')",
		backgroundSize: "cover",
		backgroundPosition: "center",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
		height: "100%",
		width: "100%",
	}));

    const form = craftingStyles(() => ({
		background: "rgba(255, 255, 255, 0.2)",
		backdropFilter: "blur(8px)",
		borderRadius: "16px",
		border: "1px solid rgba(255, 255, 255, 0.3)",
		boxShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",
		boxSizing: "border-box",
		display: "flex",
		gap: "50px",
		flexDirection: "column",
		justifyContent: "center",
		alignItems: "center",
		fontFamily: "'Exo 2', sans-serif",
		padding: "80px",
		height: "auto",
		width: "30%",
	}));

	const title = craftingStyles(() => ({
		fontFamily: "'Metamorphous', serif",
		fontSize: "30px",
		textTransform: "capitalize",
	}));

    const inputContainer = craftingStyles(() => ({
		display: "flex",
		flexDirection: "column",
		justifyContent: "center",
		alignItems: "center",
		height: "auto",
		width: "100%",
	}));

    const label = craftingStyles(() => ({
		height: "auto",
		width: "85%",
	}));

    const input = craftingStyles(() => ({
		background: "rgba(255, 255, 255, 0.27)",
		backdropFilter: "blur(10px)",
		borderRadius: "16px",
		border: "1px solid rgba(255, 255, 255, 0.51)",
		boxShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",
		boxSizing: "border-box",
		padding: "10px",
		marginTop: "10px",
		marginBottom: "40px",
		height: "50px",
		width: "90%",
	}));

    const button = craftingStyles(() => ({
		background: "rgba(255, 255, 255, 1)",
		borderRadius: "16px",
		border: "1px solid rgba(255, 255, 255, 0.8)",
		boxShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",
		boxSizing: "border-box",
		cursor: "pointer",
		fontWeight: "bold",
		fontSize: "14px",
		padding: "10px",
		height: "60px",
		width: "60%",
		hover: {
			background: "rgba(255, 255, 255, .7)",
		}
	}));

    return (
        <div className={container}>
            <form className={form}>
				<h4 className={title}>Galadriel.CSS</h4>
                <div className={inputContainer}>
                    <label className={label} htmlFor="email">
                        E-mail:
                    </label>
                    <input className={input}
                        name="email"
                        type="email"
                        placeholder="Type your e-mail"
                        required
                    />
                    <label className={label} htmlFor="password">
                        Password:
                    </label>
                    <input className={input}
                        name="password"
                        type="password"
                        placeholder="Type your password"
                        required
                    />
                </div>
                <button className={button} type="submit">
                    Login
                </button>
            </form>
        </div>
    );
}
